// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ7hYfQGFtJNZe-LO--K8TzFeslC1y9vk',
    appId: '1:1035771206342:web:3dc91c9052ece7f66e15c7',
    messagingSenderId: '1035771206342',
    projectId: 'kilumbu-dfb99',
    authDomain: 'kilumbu-dfb99.firebaseapp.com',
    storageBucket: 'kilumbu-dfb99.firebasestorage.app',
    measurementId: 'G-FNGL56Q2F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaWV05v8ZuyCRzljiX4iEiLPXNex5QcEg',
    appId: '1:1035771206342:android:e9b680089f5917846e15c7',
    messagingSenderId: '1035771206342',
    projectId: 'kilumbu-dfb99',
    storageBucket: 'kilumbu-dfb99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjwaK6J5npaKizclO3RiUao41Lmde86ng',
    appId: '1:1035771206342:ios:3bd3f1bd1afaa19d6e15c7',
    messagingSenderId: '1035771206342',
    projectId: 'kilumbu-dfb99',
    storageBucket: 'kilumbu-dfb99.firebasestorage.app',
    iosBundleId: 'com.example.sabedoria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjwaK6J5npaKizclO3RiUao41Lmde86ng',
    appId: '1:1035771206342:ios:3bd3f1bd1afaa19d6e15c7',
    messagingSenderId: '1035771206342',
    projectId: 'kilumbu-dfb99',
    storageBucket: 'kilumbu-dfb99.firebasestorage.app',
    iosBundleId: 'com.example.sabedoria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ7hYfQGFtJNZe-LO--K8TzFeslC1y9vk',
    appId: '1:1035771206342:web:b6e22e3583200faf6e15c7',
    messagingSenderId: '1035771206342',
    projectId: 'kilumbu-dfb99',
    authDomain: 'kilumbu-dfb99.firebaseapp.com',
    storageBucket: 'kilumbu-dfb99.firebasestorage.app',
    measurementId: 'G-9QNMLE8HND',
  );
}
